### ISSUE TITLE
Skip partitioning as new option

### ISSUE THREAD

**Issue by erikdubois** [spookykidmm/zen_installer#11]
I am testing out this installer and I had already installed arch linux and lxde. So partitioning was already behind me.

Wondered if the possibility could be added to skip certain functions altogether and just be able to install packages for example.

**Comment by spookykidmm** [comment]
I think this would be best left for the user to do through a package
manager. However, I am interested in possibly creating a small system
rescue program that just acts to repair some of the small things that can
mess up someone's system if a mistake occurs. Reenabling the display
manager, kernel and grub configs, maybe installing desktops. May look at
that in future releases
