### ISSUE TITLE
Getting "Minimal BASH like line editing is supported GRUB" Error

### ISSUE THREAD

**Issue by StefanVonRanda** [spookykidmm/zen_installer#13]
Seems like the installer doesn't set up grub quite right. Tried manual and automatic partitioning, but I get the same result every time.

I'm running 2 drives with Windows installed on one drive. and Manjaro on the other.

**Comment by spookykidmm** [comment]
I'm so sorry for this. When I released the ISO, everything worked, but arch introduced a new change for some reason where there's a base metapackage that doesn't pull in a kernel, linux-firmware, or a text editor. So I have to explicitly declare essentially the whole base group in the ISO, which is....fun

**Comment by StefanVonRanda** [comment]
Thanks for the reply. It's cool, I just wanted to bring it your attention in case you didn't already know about the issue.

Is there any way for me to fix this on my end?

**Comment by spookykidmm** [comment]
Yeah, let me lay it out for you:
Boot Zen ISO
Check Internet connection
Ctrl Alt T for terminal
sudo mount (your root partition) /mnt
Pacstrap/mnt linux linux-firmware
And then update your grub from one of your your other systems or
grub-install --target=i386-pc (the device you want grub on)

**Comment by spookykidmm** [comment]
Oh sorry, if you're installing grub to boot all your systems
Sudo pacman -S os-prober
pacstrap /mnt os-prober
Before the grub-install command
