### ISSUE TITLE
Root shell set to '/usr/bin/' after install

### ISSUE THREAD

**Issue by muhgrill** [spookykidmm/zen_installer#2]
After install I was unable to `sudo su -` with my user, even though sudo otherwise seems to be working properly.
```
$ sudo su -
su: failed to execute /usr/bin/: Permission denied
```

This appears to be because root's shell is set to '/usr/bin/'.
`root:x:0:0::/root:/usr/bin/`

Changing the default shell to /bin/bash resolves all issue.

I'm guessing the issue is with this line. https://github.com/spookykidmm/zen_installer/blob/b566c7b16882cd712987999437576c4779bfa777/zif#L560

Checking to see if $shell is set or setting a default might help to resolve.

**Comment by spookykidmm** [comment]
Think I fixed it. Thanks for pointing that out!
