### ISSUE TITLE
Not so much of an issue as a request?

### ISSUE THREAD

**Issue by mrgreen3** [spookykidmm/zen_installer#3]
Would it be possible to use this under ArchBang iso? Given a user needs a working network connection could I add a small script to source script and run it?

**Comment by spookykidmm** [comment]
Wait, I have to ask. Are you THE mrgreen?

**Comment by mrgreen3** [comment]
Might be ;-) .... sorry I could not find an email or contact details on source forge (certainly not going to look on arch linux forums) 

I am quite lazy when it comes to installers, been asked once again for a network based one. Was told revenge did not have UEFI support (but looking at zen it does).

Mr Green

www.archbang.org

**Comment by spookykidmm** [comment]
I'm sorry, I recently revamped a lot of stuff and I haven't quite updated everything. You can email me at zeninstaller at tutanota dot com. You can absolutely use Zen, but I'd love to talk to you more
