### ISSUE TITLE
Misdetection of Intel processor by grub installation

### ISSUE THREAD

**Issue by squirrelfan** [spookykidmm/zen_installer#6]
I have a AMD CPU but the Installation seems not to have detected it correctly, so I wonder.

In the grub.cfg is stated something like:
initrd Intel-ucode.img Linux-lts.img

But should be:
initrd Intel-ucode.img Linux-lts.img

**Comment by squirrelfan** [comment]
I had to install amd-ucode.

Now the grub.cfg-entry is:
initrd  /boot/intel-ucode.img /boot/amd-ucode.img /boot/initramfs-linux-lts.img

This should work for all cases, I think.

**Comment by spookykidmm** [comment]
Yep, I think I added an option to detect it properly in the future. Testing now
