### ISSUE TITLE
Request:Please install os-prober

### ISSUE THREAD

**Issue by squirrelfan** [spookykidmm/zen_installer#7]
Please install os-prober before generating grub.cfg so that the other operating Systems on my pc could also be found and started.

**Comment by spookykidmm** [comment]
I think I had an issue with installing os-prober early on. Best option would be to just install it on your new system upon reboot and update your grub. I guess i could install it only if the user asks to install grub

**Comment by squirrelfan** [comment]
So I think when the user installs grub he would expect that there is os-prober also, so he can boot other systems, too, not only the new installed. If this seems to difficult so please at least make a notice.
